# Generated by Django 3.2.6 on 2021-09-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashinne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashinne.category'),
        ),
    ]
