# Generated by Django 3.2.6 on 2021-09-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashinne', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
